# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Teaching"
url = "pricing/"
weight = 2

[[main]]
name = "Tools"
url = "tools/"
weight = 3

[[main]]
name = "Publications"
url = "pages/publications"
weight = 4

[[main]]
name = "Gallery"
url = "gallery/"
weight = 5

# footer menu left
# [[footer_left]]
# name = "About Us"
# url = "#"

# [[footer_left]]
# name = "Quick Start"
# url = "#"

# [[footer_left]]
# name = "Pricing"
# url = "pricing/"


# footer menu middle
# [[footer_middle]]
# name = "Pricing"
# url = "pricing/"

# [[footer_middle]]
# name = "Platform"
# url = "#"

# [[footer_middle]]
# name = "Features"
# url = "#"

# footer menu right
# [[footer_right]]
# name = "Privacy Policy"
# url = "privacy-policy/"

# [[footer_right]]
# name = "Terms & Conditions"
# url = "terms-conditions/"

# [[footer_right]]
# name = "FAQ"
# url = "faq/"
