#################### default parameters ################################
logo = "images/logo.png"
logo_width = "100px"
# OpenGraph / Twitter Card metadata
description = "SCIL web site"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = false
label = "Get Started"
link = "contact"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/SCIL.2500"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/maxdescoteaux"

[[social]]
title = "github"
icon = "fab fa-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/scilus"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/maxime-descoteaux-2445701/"
